### ISSUE TITLE
Links don't inherit color in Firefox

### ISSUE THREAD

**Issue by LorenzHenk** [itsmelion/flamework#4]
In Firefox (Mozilla Firefox 71.0) colors of links are not set and thus unreadable on your website. It's fine in Google Chrome.

![image](https://user-images.githubusercontent.com/10603631/73267911-3f5da880-41da-11ea-928f-a332d02ffe4a.png)

![image](https://user-images.githubusercontent.com/10603631/73267929-45538980-41da-11ea-8ac4-e887bf604365.png)

To fix the problem, apply the following style:

```css
.link, :any-link, :link, a[href] {
  color: unset;
}
```
